backend:
  name: github
  repo: yusufkocak01/fizikadana   # GitHub repo adı
  branch: main                    # İçerik hangi branch’te tutulacak
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "images"            # Dosyaların kaydedileceği klasör (repo içi)
public_folder: "/images"          # Web’de kullanılacak yol

collections:
  - name: "pages"
    label: "Sayfalar"
    files:
      - file: "hakkimda.html"
        label: "Hakkımızda"
        fields:
          - label: "Başlık"
            name: "title"
            widget: "string"
          - label: "İçerik"
            name: "body"
            widget: "markdown"
