name: Deploy to Google Cloud Storage

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove .git folder
        run: |
          rm -rf .git

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload to GCS
        run: |
          gsutil -m rsync -r ./ gs://fizikadana.com
        env:
          CLOUDSDK_CORE_PROJECT: Sitelerim
