name: Deploy to Google Cloud Storage

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Google Cloud'a kimlik doğrulaması
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Tüm dosyaları GCS'e yükle
      - name: Upload to GCS
        run: |
          gsutil -m rsync -r -d ./ gs://fizikadana.com
        env:
          CLOUDSDK_CORE_PROJECT: Sitelerim
